[package]
name = "odbc-tools"
version = "0.1.0"
authors = ["Jakub Pastuszek <jpastuszek@gmail.com>"]
edition = "2018"

[dependencies]
cotton = { git = "https://github.com/jpastuszek/cotton.git" }
structopt = "0.2.14"
odbc-iter = { git = "https://github.com/jpastuszek/odbc-iter.git", features = ["serde_json"] }
